javax:
  sql:
    DataSource:
      prueba:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost:5433/distribuida
          user: postgres
          password: postgres
